#!/bin/bash -e

# Find modified C++ source files, exit if none found
FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(cpp|cppm)$"`|| exit 0

for FILE in $FILES; do
	/usr/bin/astyle --project $FILE
done
